GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTE0MTUiLCJpZCI6IjY2NjJkZjJhMzI3N2E3ODc1MDFlYjRkZCIsImlhdCI6MTcxNzc1NzYxNywiZXhwIjoxNzE3NzYxMjE3fQ.GoyBeYrsEUCUjJXuCts2b5YAIWNqN5GEOUkH3Ui-6Ds
  
  {  
    "title": "hello again again hello",
    "author": "Nabina",
    "url": "https://en.wikipedia.org/wiki/One_Piece",
    "likes": 20,
    "userId":"6662df2a3277a787501eb4dd"
}
###
DELETE http://localhost:3003/api/blogs/6662e6ce35f862a88f4763d5
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTE0MTUiLCJpZCI6IjY2NjJkZjJhMzI3N2E3ODc1MDFlYjRkZCIsImlhdCI6MTcxNzc1NzgzMCwiZXhwIjoxNzE3NzYxNDMwfQ.9MvpI8PaM_AeFAsEbd1BHRll6Dpn2JThY4HLhuefFr0
 
  {  
    "title": "hello again again hello",
    "author": "Nabina",
    "url": "https://en.wikipedia.org/wiki/One_Piece",
    "likes": 20,
    "userId":"6662df2a3277a787501eb4dd"

}
###
PUT http://localhost:3003/api/blogs/6656b8dbeb25bd3b8bd163f5
Content-Type: application/json

{
    "likes": 0
    
}

###
POST http://localhost:3003/api/users
content-type: application/json

{ 
    "username": "nabina14156",
    "name":"Nabina1415 ",  
    "password":"nabina123"
}

###
POST http://localhost:3003/api/login/
content-type: application/json

{
    
    "username": "nabina1415",
    "password":"nabina123"
}
