GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"forth Blog",
    "author":"Nabina",
    "url":"https://en.wikipedia.org/wiki/One_Piece",
    "likes":5,
    "userId":"665edfc9176dd14ffac947db"
}
###
DELETE http://localhost:3003/api/blogs/6656b8c4eb25bd3b8bd163f0
###
PUT http://localhost:3003/api/blogs/6656b8dbeb25bd3b8bd163f5
Content-Type: application/json

{
    "likes": 0
    
}

###
POST http://localhost:3003/api/users
content-type: application/json

{ 
    "username": "na",
    "name":"Na ",  
    "password":"nabina123"
}
